### ISSUE TITLE
Emoji URLs

### ISSUE THREAD

**Issue by aaronflorey** [nilobarp/summernote-ext-emoji#1]
Need to be able to choose where the emoji's are located

**Comment by nilobarp** [comment]
We can't pass options to the plugin from Summernote toolbar configuration. Currently the only way to change path is to edit it in source.

**Comment by nilobarp** [comment]
Just as a work around, now reads `emojiSource` from `document` property. 73c8027c3ab6bb71f9627fbcc1c1b5c16ccd754a 

add `document.emojiSource = '../pngs/'` before calling the plugin.

**Comment by RokSiEu** [comment]
I think that it is better to use

```
mojiSource= window.location.origin+'path/to/emoji/'; 
```

this way it will always look in folder domain.com/path/to/emoji/

**Comment by nilobarp** [comment]
@RokSiEu Your approach is best when the same script needs to be included in multiple pages :+1:
