### ISSUE TITLE
Undefined method getEditor

### ISSUE THREAD

**Issue by thyagorafaell** [nilobarp/summernote-ext-emoji#3]
I'm using Summernote 0.6.9, and in this version the method $.summernote.eventHandler.getEditor is undefined.

It's on file src/summernote-ext-emoji.js, line 13:
var editor = $.summernote.eventHandler.getEditor();

Is this var used?

**Comment by nilobarp** [comment]
I didn't upgrade to latest summernote. Just tested and that `var` is not used, so you can safely remove it.
