### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTemplate' of undefined

### ISSUE THREAD

**Issue by audas** [nilobarp/summernote-ext-emoji#4]
Latest summernote.

**Comment by pashakiz** [comment]
the same errror...

**Comment by jasontduncan** [comment]
Summernote hard-deprecated (completely changed) their plugin API. This plugin won't work with versions >= v0.7.0. Seems abandoned.

**Comment by ArnoldPMolenaar** [comment]
I have pulled a new requests. With this update you can use it for the newest summernote versions

**Comment by nilobarp** [comment]
Updated to work with summernote 0.7.0 +
